// =================== jira ==================

// login
export const SIGN_IN_SAGA = 'SIGN_IN_SAGA';
export const SIGN_IN = 'SIGN_IN';
export const CATCH_ERROR = 'CATCH_ERROR';

// Project
// saga
export const GET_CATEGORY_PROJECT_API_SAGA = 'GET_CATEGORY_PROJECT_API_SAGA';
export const CREATE_PROJECT_AUTHORIZATION_SAGA = 'CREATE_PROJECT_AUTHORIZATION_SAGA';
export const GET_PROJECT_API_SAGA = 'GET_PROJECT_API_SAGA';
export const SEARCH_USER_API_SAGA = 'SEARCH_USER_API_SAGA';
export const SEARCH_USER_API = 'SEARCH_USER_API';
export const ADD_USER_API_SAGA = 'ADD_USER_API_SAGA';
export const GET_PROJECT_DETAILS_SAGA = 'GET_PROJECT_DETAILS_SAGA';
export const EDIT_PROJECT_SAGA = 'EDIT_PROJECT_SAGA';
export const DELETE_PROJECT_API_SAGA = 'DELETE_PROJECT_API_SAGA';
export const REMOVE_USER_PROJECT_SAGA = 'REMOVE_USER_PROJECT_SAGA';
export const GET_PRIORITIES_API_SAGA = 'GET_PRIORITIES_API_SAGA';
export const GET_TASK_TYPE_API_SAGA = 'GET_TASK_TYPE_API_SAGA';
export const GET_USER_SAGA = 'GET_USER_SAGA';
export const GET_STATUS_SAGA = 'GET_STATUS_SAGA';
export const CREATE_TASK_SAGA = 'CREATE_TASK_SAGA';
export const GET_TASK_DETAIlS_SAGA = 'GET_TASK_DETAIlS_SAGA';
export const CHANGE_STATUS_TASK_DETAIL_SAGA = 'CHANGE_STATUS_TASK_DETAIL_SAGA';
export const ASSIGN_USER_TASK_SAGA = 'ASSIGN_USER_TASK_SAGA';
export const UPDATE_TASK_SAGA = 'UPDATE_TASK_SAGA';
export const GET_ALL_COMMENT_SAGA = 'GET_ALL_COMMENT_SAGA';
export const SIGN_UP_SAGA = 'SIGN_UP_SAGA';
export const EDIT_USER_SAGA = 'EDIT_USER_SAGA';
export const DELETE_USER_SAGA = 'DELETE_USER_SAGA';

// reducer
export const GET_CATEGORY_PROJECT_API = 'GET_CATEGORY_PROJECT_API';
export const GET_PROJECT_API = 'GET_PROJECT_API';
export const EDIT_PROJECT = 'EDIT_PROJECT';
export const GET_PROJECT_DETAILS = 'GET_PROJECT_DETAILS';
export const GET_PRIORITIES_API = 'GET_PRIORITIES_API';
export const GET_TASK_TYPE_API = 'GET_TASK_TYPE_API';
export const GET_USER = 'GET_USER';
export const GET_STATUS = 'GET_STATUS';
export const CREATE_TASK = 'CREATE_TASK';
export const CHANGE_MODAL_PROJECTDETAIL_REDUCER = 'CHANGE_MODAL_PROJECTDETAIL_REDUCER';
export const GET_TASK_DETAIlS_REDUCER = 'GET_TASK_DETAIlS_REDUCER';
export const CHANGE_STATUS_TASK_DETAIL = 'CHANGE_STATUS_TASK_DETAIL';
export const ASSIGN_USER_TASK_REDUCER = 'ASSIGN_USER_TASK_REDUCER';
export const UPDATE_TASK_REDUCER = 'UPDATE_TASK_REDUCER';
export const GET_REPOTER = 'GET_REPOTER';
export const GET_ALL_COMMENT = 'GET_ALL_COMMENT';
export const CHANGE_SEARCH_TEXT = 'CHANGE_SEARCH_TEXT';
export const CHANGE_VISIBLE_MODAL_EDIT_USER = 'CHANGE_VISIBLE_MODAL_EDIT_USER';
export const EDIT_USER = 'EDIT_USER';
// HISTORY REDUCER
export const CHANGE_HISTORY = 'CHANGE_HISTORY';

// LOADING REDUCER
export const CHANGE_LOADING = 'CHANGE_LOADING';

// DRAWER REDUCER

export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';

//-------------------------------------------------
export const STATUS_API = {
	SUCCESS: 200,
	FAIL: 400,
};

//---------------------------------------------------
export const ACCESS_TOKEN = 'ACCESS_TOKEN';
export const USER = 'USER_LOGIN';
