import { all } from 'redux-saga/effects';
import {
	watchActionCreateProject,
	watchActionGetProjectAPI,
	watchActionSignInJira,
	watchActionGetAllProjects,
	watchActionEditProjectSaga,
	watchActionDeleteProjectSaga,
	watchActionSearchUserApi,
	watchActionAddUserProject,
	watchActionRemoveUserProject,
	watchActionGetProjectDetails,
	watchActionGetPriorities,
	watchActionGetTaskType,
	watchActionGetUser,
	watchActionGetStatus,
	watchActionCreateTask,
	watchActionGetTaskDetail,
	watchActionChangeStatusTaskDetail,
	watchActionAssignUserTask,
	watchActionUpdateTask,
	watchActionGetAllComments,
	watchActionSignUp,
	watchActionEditUser,
	watchActionDeleteUser,
	watchActionInsertComment,
	watchActionUpdateComment,
	watchActionDeleteComment,
} from './jiraSaga/JiraSaga';

export default function* rootSaga() {
	yield all([
		watchActionSignInJira(),
		watchActionGetProjectAPI(),
		watchActionCreateProject(),
		watchActionGetAllProjects(),
		watchActionEditProjectSaga(),
		watchActionDeleteProjectSaga(),
		watchActionSearchUserApi(),
		watchActionAddUserProject(),
		watchActionRemoveUserProject(),
		watchActionGetProjectDetails(),
		watchActionGetPriorities(),
		watchActionGetTaskType(),
		watchActionGetUser(),
		watchActionGetStatus(),
		watchActionCreateTask(),
		watchActionGetTaskDetail(),
		watchActionChangeStatusTaskDetail(),
		watchActionAssignUserTask(),
		watchActionUpdateTask(),
		watchActionGetAllComments(),
		watchActionSignUp(),
		watchActionEditUser(),
		watchActionDeleteUser(),
		watchActionInsertComment(),
		watchActionUpdateComment(),
		watchActionDeleteComment(),
	]);
}
